version: '3.5'
services:


  mongo:
    image: mongo:4.2.11
    restart: always
    command: --nojournal
    ports:
      - 27027:27017
    volumes:
      - './mongo_data:/data/db'

  geodata-be:
    image: geodata-be:beta
    container_name: "geodata-be"
    build:
      context: .
    depends_on:
      - mongo
    restart: always
    ports:
      - '9090:9090'
    environment:
      - SERVER_PORT=9090
      - HOST_ORION=https://orion.ecosystem-urbanage.eu
      - MONGODB_URL=mongodb://mongo
      - PLATFORM=prod #prod

