version: '3.5'
services:
#   mongodb:
#    image: mongo:3.6
#    hostname: mongodb
#    container_name: db-mongo
#    restart: always
#    ports:
#     - '27017:27017'
#    command: --bind_ip_all
#    volumes:
#     - ./data:/data/db
#    networks:
#     - simulator   
#   orion:
#    image: fiware/orion-ld
#    hostname: orion
#    restart: always
#    container_name: fiware-orion-ld
#    expose:
#     - '1026'
#    ports:
#      - '127.0.0.1:1026:1026'
#    depends_on:
#      - mongodb
#    command: -dbhost mongodb
#    networks:
#     - simulator

  geodata-be:
    image: geodata-be:main
    container_name: "geodata-be"
    build:
      context: .
# depends_on:
#   - mongodb
    restart: always
    ports:
      - '9090:9090'
    environment:
      - SERVER_PORT=9090
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_DATABASE_NAME=orion
      - MONGO_URI=mongodb://mongo:27017/orion
      - HOST_ORION=orion.dev.ecosystem-urbanage.eu
      - PORT_ORION=443

