services:
  mongo:
    image: mongo:4
    restart: always
    command: --nojournal
    ports:
      - 27027:27017
    volumes:
      - './mongo_data:/data/db'

  geodata-be:
    image: geodata-be:main
    container_name: "geodata-be"
    build:
      context: .
    depends_on:
      - mongo
    restart: always
    ports:
      - '9090:9090'
    environment:
      - SERVER_PORT=9090
      - SERVER_URL=http://localhost
      - HOST_ORION=http://172.16.10.173:1026
      - HOST_NGSIBROKER=https://ngsi-broker.dev.ecosystem-urbanage.eu
      - MONGODB_URL=mongodb://mongo
      - PLATFORM=dev #prod
